service: kmnv-backend

useDotenv: true

plugins:
  - serverless-offline

provider:
  name: aws
  runtime: nodejs20.x
  enviroment:
    DATABASE_URL: ${env:DATABASE_URL}
    ACCESS_TOKEN_SECRET: ${env:ACCESS_TOKEN_SECRET}
    REFRESH_TOKEN_SECRET: ${env:REFRESH_TOKEN_SECRET}

    AWS_ACCESS_KEY: ${env:AWS_ACCESS_KEY}
    AWS_SECRET_ACCESS_KEY: ${env:AWS_SECRET_ACCESS_KEY}
    AWS_S3_REGION: ${env:AWS_S3_REGION}

    PORT: ${env:PORT}

    UPLOAD_RATE_TTL: ${env:UPLOAD_RATE_TTL}
    UPLOAD_RATE_LIMIT: ${env:UPLOAD_RATE_LIMIT}

functions:
  main:
    handler: dist/serverless.handler
    events:
      - http:
          method: ANY
          path: /
      - http:
          method: ANY
          path: '{proxy+}'
